sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKeynBbTkuiDSUBKQEv
    access-key-secret:
    bucket-name: sky0614
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx7748bbb61f0d449b
    secret:
    # 商户号
    mchid:
    # 商户API证书的证书序列号
    mch-serial-no:
    # 商户私钥文件
    private-key-file-path:
    # 证书解密的密钥
    api-v3-key:
    # 平台证书
    we-chat-pay-cert-file-path:
    # 支付成功的回调地址
    notify-url:
    # 退款成功的回调地址
    refund-notify-url:

